import turtle
screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('pink')
t = turtle.Turtle()
t.speed(0)

t.penup()
t.goto(0, 200)
t.pendown()
t.write("Turtle Presentation", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0,0)
t.pendown()

t.penup()
t.goto(0, 150)
t.pendown()
t.write("By: Maci Prokop", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0,0)
t.pendown()

t.penup()
t.goto(0, 100)
t.pendown()
t.write("Press Enter to Continue", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0,0)
t.pendown()

t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('sun.gif')
t.shape('sun.gif')
t.stamp()
t.shape('classic')


t.penup()
t.goto(-150,-50)
t.pendown()
screen.addshape('beach.gif')
t.shape('beach.gif')
t.stamp()
t.shape('classic')


t.fillcolor('white')
t.begin_fill()
t.penup()
t.goto(300,-300)
t.pendown()
t.left(90)
t.forward(160)
t.left(90)
t.forward(100)
t.left(90)
t.forward(160)
t.left(90)
t.forward(100)
t.end_fill()


round = input("Press Enter to Continue: ")
screen.bgcolor('purple')
t.clear()

t.penup()
t.goto(0, 300)
t.pendown()
t.write("Favorite Foods", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0, 200)
t.pendown()
t.write("Press Enter to Continue", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0,0)
t.pendown()


t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('turtle5leg.gif')
t.shape('turtle5leg.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(0,-50)
t.pendown()
screen.addshape('pineapple.gif')
t.shape('pineapple.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-170,-50)
t.pendown()
screen.addshape('grilled.gif')
t.shape('grilled.gif')
t.stamp()
t.shape('classic')

t.fillcolor('lightblue')
t.begin_fill()
t.penup()
t.goto(300,-300)
t.pendown()
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

round = input("Press Enter to Continue: ")
screen.bgcolor('lightblue')
t.clear()

t.penup()
t.goto(0, 300)
t.pendown()
t.write("Favorite Hobbies", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0, 200)
t.pendown()
t.write("Press Enter to Continue", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0,0)
t.pendown()


t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('shop.gif')
t.shape('shop.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-60,-50)
t.pendown()
screen.addshape('swim.gif')
t.shape('swim.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-120,-260)
t.pendown()
screen.addshape('music.gif')
t.shape('music.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-300)
t.pendown()
screen.addshape('track.gif')
t.shape('track.gif')
t.stamp()
t.shape('classic')

t.fillcolor('lightpink')
t.begin_fill()
t.penup()
t.goto(-200,0)
t.pendown()
t.circle(25)
t.setheading(90)
t.end_fill()


round = input("Press Enter to Continue: ")
screen.bgcolor('coral')
t.clear()

t.penup()
t.goto(0, 300)
t.pendown()
t.write("Favorite Movies", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0, 200)
t.pendown()
t.write("Press Enter to Continue", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0,0)
t.pendown()

t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('mean.gif')
t.shape('mean.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-150,-50)
t.pendown()
screen.addshape('girl.gif')
t.shape('girl.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(110,110)
t.pendown()
t.fillcolor('purple')
t.begin_fill()
t.goto(210,110)
t.goto(160,210)
t.goto(110,110)
t.end_fill()

round = input("Press Enter to Continue: ")
screen.bgcolor('pink')
t.clear()

t.penup()
t.goto(0, 300)
t.pendown()
t.write("Favorite Sports", font=('Arial', 30, "normal"), align="center")
t.penup()
t.goto(0, 200)
t.pendown()


t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('run1.gif')
t.shape('run1.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-150,-50)
t.pendown()
screen.addshape('jog.gif')
t.shape('jog.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-100,-200)
t.pendown()
t.pencolor('lightblue')
t.setheading(50)
t.pensize(5)
t.fillcolor('red')
t.begin_fill()
t.circle(50,180)


turtle.done()